version: '3.8'

services:
  bot:
    build: .
    container_name: pyro_serval_bot
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - BOT_TOKEN=${BOT_TOKEN}
      - DB_URL=${DB_URL}
      - ENGINE_URL=${ENGINE_URL}
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:13
    container_name: pyro_serval_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pyroserval
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
