"""Recreate users table 2

Revision ID: 5299436c57d9
Revises: ec382f03cc55
Create Date: 2024-06-12 17:55:47.138712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5299436c57d9'
down_revision: Union[str, None] = 'ec382f03cc55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('status_updated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_message_time', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('message_text', sa.String(), nullable=True))
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_column('users', 'email')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('users', 'message_text')
    op.drop_column('users', 'last_message_time')
    op.drop_column('users', 'status_updated_at')
    op.drop_column('users', 'status')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
