"""Initial migration

Revision ID: d3ffb754d5e0
Revises: 
Create Date: 2024-06-10 03:04:28.974308

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd3ffb754d5e0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('status', sa.Enum('ALIVE', 'DEAD', 'FINISHED', name='statusenum'), nullable=True),
                    sa.Column('status_updated_at', sa.DateTime(), nullable=True),
                    sa.Column('last_message_time', sa.DateTime(), nullable=True),
                    sa.Column('message_text', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
