"""Recreate users table

Revision ID: ec382f03cc55
Revises: 0d1738c00d98
Create Date: 2024-06-12 17:24:09.666214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec382f03cc55'
down_revision: Union[str, None] = '0d1738c00d98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'users',
        sa.Column('id', sa.BigInteger, primary_key=True),
        sa.Column('created_at', sa.DateTime, nullable=False),
        sa.Column('status', sa.String(50), nullable=False),
        sa.Column('status_updated_at', sa.DateTime, nullable=False),
        sa.Column('last_message_time', sa.DateTime, nullable=False),
        sa.Column('message_text', sa.String(255), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
